apiVersion: v1
kind: Pod
metadata:
  name: fill-pvc
  namespace: default
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/data/testfile bs=1M count=100000"]
    volumeMounts:
    - name: data
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test-pvc
