apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumania
  namespace: {{ .Release.Namespace }}
  labels:
    app: volumania
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: volumania
  template:
    metadata:
      labels:
        app: volumania
    spec:
      serviceAccountName: volumania
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: {{ .Values.kubernetes.serviceHost | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
