apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumania
  labels:
    app: volumania
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: volumania
  template:
    metadata:
      labels:
        app: volumania
    spec:
      serviceAccountName: volumania
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROMETHEUS_URL
              value: {{ .Values.prometheus.url | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
