apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumania
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumania
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["scaling.volumania.io"]
    resources: ["pvcautoscalers", "pvcautoscalers/status", "pvcmanualresizes", "pvcmanualresizes/status"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]  
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volumania
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: volumania
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: volumania
    namespace: {{ .Release.Namespace }}
