apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumania
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumania
rules:
  - apiGroups: ["", "scaling.volumania.io"]
    resources: ["persistentvolumeclaims", "pvcautoscalers", "pvcmanualresizes"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volumania
roleRef:
  kind: ClusterRole
  name: volumania
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: volumania
    namespace: default
