replicaCount: 1

image:
  repository: ghcr.io/therealpoys/volumania
  tag: cb6426ae6b054e63cd13fe4c7ae35bfec09ddf32
  pullPolicy: IfNotPresent

imagePullSecret: ghcr-secret  

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

prometheus:
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
