replicaCount: 1

image:
  repository: ghcr.io/therealpoys/volumania
  tag: dev-dev
  pullPolicy: IfNotPresent

imagePullSecret: ghcr-secret  

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

kubernetes:
  serviceHost: kubernetes.default.svc
