apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumania-backend
  labels:
    app: volumania-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumania-backend
  template:
    metadata:
      labels:
        app: volumania-backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources: {{- toYaml .Values.resources | nindent 12 }}
