apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pvcautoscalers.scaling.volumania.io
spec:
  group: scaling.volumania.io
  names:
    kind: PVCAutoScaler
    plural: pvcautoscalers
    singular: pvcautoscaler
    shortNames:
      - pvcauto
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [pvcName, maxSize, stepSize]
              properties:
                pvcName:
                  type: string
                  description: Name of the PersistentVolumeClaim to autoscale
                minSize:
                  type: string
                  pattern: '^[0-9]+Gi$'
                  description: Minimum allowed size of the PVC
                maxSize:
                  type: string
                  pattern: '^[0-9]+Gi$'
                  description: Maximum allowed size of the PVC
                stepSize:
                  type: string
                  pattern: '^[0-9]+Gi$'
                  description: Amount to grow the PVC by each time scaling is triggered
                triggerAbovePercent:
                  type: integer
                  minimum: 1
                  maximum: 100
                  default: 80
                  description: Usage percentage that triggers an autoscale
                checkIntervalSeconds:
                  type: integer
                  default: 60
                  description: Interval in seconds between usage checks
                cooldownSeconds:
                  type: integer
                  default: 600
                  description: Minimum delay in seconds between scaling events
                enabled:
                  type: boolean
                  default: true
                  description: Whether autoscaling is active
            status:
              type: object
              properties:
                currentSize:
                  type: string
                  description: Current observed size of the PVC
                lastScaleTime:
                  type: string
                  format: date-time
                  description: Timestamp of the last resize operation
                reason:
                  type: string
                  description: Explanation for the last scale event or error
