name: Build & Push Volumania Images

on:
  push:
    branches:
      - '**'  
    tags:
      - 'v*'  

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract tag and metadata
        id: meta
        run: |
          echo "sha=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "is_main=$([[ '${{ github.ref }}' == 'refs/heads/main' ]] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "is_tag=$([[ '${{ github.ref }}' == refs/tags/* ]] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.sha }}
            ${{ steps.meta.outputs.is_main == 'true' && format('ghcr.io/{0}:latest', github.repository) || '' }}
            ${{ steps.meta.outputs.is_tag == 'true' && format('ghcr.io/{0}:{1}', github.repository, github.ref_name) || '' }}
            ${{ steps.meta.outputs.is_main != 'true' && steps.meta.outputs.is_tag != 'true' && format('ghcr.io/{0}:dev-{1}', github.repository, steps.meta.outputs.branch) || '' }}
